- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: restart alertmanager service
  service:
    name: alertmanager
    state: restarted
  listen: event_restart_alertmanager