route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - matchers:
      - severity="critical"
    receiver: 'discord'
  receiver: 'discord'

receivers:
  - name: "discord"
    discord_configs:
      - webhook_url: 'https://discordapp.com/api/webhooks/1349006595325038682/PKZMtHoIbzQZGpB5_scwpD3MDjqTCkbcWiBHjNE998qW351t1cogxk-rOyoIByO9dyiQ'

